name:                rubik
version:             0.1.1
license:             AllRightsReserved
author:              "Boris Tschochner"
maintainer:          "tschochner@hornetsecurity.com"
copyright:           ""

extra-source-files:
- README.md

description:         See README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -fno-warn-orphans

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveDataTypeable
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- TemplateHaskell
- LambdaCase
- MonoLocalBinds
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances

library:
  source-dirs: src
  dependencies:
  - ansi-terminal
  - base 
  - bytestring
  - colour
  - formatting
  - ini
  - monad-control
  - mtl
  - text
executables:
  rubik:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # do not run parallel garbage collection
    - -with-rtsopts=-qg
    dependencies:
    - rubik
    - base
    - formatting
    - ini
    - monad-control
    - mtl
    - text
tests:
  rubik-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - rubik
      - hspec
      - mtl
      - text
  hlint:
    main:                Hlint.hs
    source-dirs:         test/hlint
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
        - base
        - hlint
